name: Listmonk RSS Campaign

on:
  schedule:
    - cron: '0 8 * * 3'  # Run every Wednesday at 8:00 AM
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv and enable caching
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install
          
    - name: Download last update artifact
      uses: actions/download-artifact@v4
      with:
        name: update-state-gh.geojson
        path: build/
      continue-on-error: true  # Allow first run when artifact doesn't exist
        
    - name: 👷 Run RSS campaign
      run: uv run python listmonk_rss.py --state-file build/last-update-gh.json
      env:
        RSS_FEED: ${{ vars.RSS_FEED }}
        LISTMONK_API_USER: ${{ vars.LISTMONK_API_USER }}
        LISTMONK_API_TOKEN: ${{ secrets.LISTMONK_API_TOKEN }}
        PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
        PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
        LISTMONK_HOST: ${{ vars.LISTMONK_HOST }}
        LIST_NAME: ${{ vars.LIST_NAME }}
        SEND_DELAY: ${{ vars.SEND_DELAY }}
        
    - name: Upload last update artifact
      uses: actions/upload-artifact@v4
      with:
        name: update-state-gh.geojson
        path: build/
        retention-days: 31
